// Liste des principales villes/communes par wilaya (Algérie)
// Utilisé pour le filtre dépendant Wilaya -> Ville
export const VILLES_PAR_WILAYA = {
  "Adrar": ["Adrar", "Reggane", "Timimoun", "Aoulef", "Zaouiet Kounta", "Tamest", "Fenoughil"],
  "Chlef": ["Chlef", "Ténès", "Boukadir", "Oued Fodda", "El Karimia", "Ouled Fares"],
  "Laghouat": ["Laghouat", "Aflou", "Ksar El Hirane", "Hassi R'Mel", "Brida"],
  "Oum El Bouaghi": ["Oum El Bouaghi", "Aïn Beïda", "Aïn M'lila", "Sigus", "Meskiana"],
  "Batna": ["Batna", "Barika", "Merouana", "Arris", "N'Gaous", "Tazoult"],
  "Béjaïa": ["Béjaïa", "Akbou", "Kherrata", "Amizour", "Sidi Aich", "Tichy", "El Kseur"],
  "Biskra": ["Biskra", "Tolga", "Sidi Okba", "Ouled Djellal", "El Kantara", "Zeribet El Oued"],
  "Béchar": ["Béchar", "Kenadsa", "Abadla", "Taghit", "Béni Abbès"],
  "Blida": ["Blida", "Boufarik", "Larbaâ", "Mouzaïa", "Bouinan", "Ouled Yaich"],
  "Bouira": ["Bouira", "Sour El Ghozlane", "Lakhdaria", "Kadiria", "M'Chedallah"],
  "Tamanrasset": ["Tamanrasset", "In Salah", "In Guezzam", "Abalessa", "Idles"],
  "Tébessa": ["Tébessa", "Bir El Ater", "Cheria", "El Aouinet", "Négrine"],
  "Tlemcen": ["Tlemcen", "Maghnia", "Ghazaouet", "Nedroma", "Remchi", "Sebdou"],
  "Tiaret": ["Tiaret", "Sougueur", "Frenda", "Mahdia", "Ksar Chellala"],
  "Tizi Ouzou": ["Tizi Ouzou", "Azazga", "Draâ Ben Khedda", "Boghni", "Larbaâ Nath Irathen", "Ouadhias"],
  "Alger": ["Alger Centre", "Bab Ezzouar", "Hydra", "El Harrach", "Bir Mourad Raïs", "Kouba", "Dar El Beïda", "Chéraga", "Bab El Oued", "Rouiba", "Zeralda", "Draria", "Birtouta"],
  "Djelfa": ["Djelfa", "Aïn Oussera", "Messaad", "Hassi Bahbah", "Charef"],
  "Jijel": ["Jijel", "Taher", "El Milia", "Chekfa", "Ziama Mansouriah"],
  "Sétif": ["Sétif", "El Eulma", "Aïn Oulmene", "Bougaâ", "Aïn Arnat"],
  "Saïda": ["Saïda", "Aïn El Hadjar", "Youb", "Sidi Boubekeur"],
  "Skikda": ["Skikda", "Collo", "Azzaba", "Aïn Kechra", "El Harrouch"],
  "Sidi Bel Abbès": ["Sidi Bel Abbès", "Telagh", "Ben Badis", "Sfisef", "Tessala"],
  "Annaba": ["Annaba", "El Bouni", "El Hadjar", "Berrahal", "Seraïdi"],
  "Guelma": ["Guelma", "Oued Zenati", "Bouchegouf", "Héliopolis"],
  "Constantine": ["Constantine", "El Khroub", "Hamma Bouziane", "Zighoud Youcef", "Aïn Smara"],
  "Médéa": ["Médéa", "Berrouaghia", "Ksar El Boukhari", "Tablat", "Aïn Boucif"],
  "Mostaganem": ["Mostaganem", "Aïn Tédelès", "Sidi Ali", "Bouguirat", "Hassi Mameche"],
  "M'Sila": ["M'Sila", "Bou Saâda", "Sidi Aïssa", "Aïn El Melh", "Magra"],
  "Mascara": ["Mascara", "Tighennif", "Sig", "Mohammadia", "Ghriss"],
  "Ouargla": ["Ouargla", "Hassi Messaoud", "Touggourt", "N'Goussa", "Témacine"],
  "Oran": ["Oran", "Es Senia", "Bir El Djir", "Aïn El Turck", "Arzew", "Bethioua", "Gdyel"],
  "El Bayadh": ["El Bayadh", "Bougtoub", "Rogassa", "Brezina"],
  "Illizi": ["Illizi", "Djanet", "Bordj Omar Driss"],
  "Bordj Bou Arréridj": ["Bordj Bou Arréridj", "Ras El Oued", "Mansourah", "El Achir"],
  "Boumerdès": ["Boumerdès", "Boudouaou", "Dellys", "Thenia", "Naciria", "Corso"],
  "El Tarf": ["El Tarf", "El Kala", "Bouteldja", "Ben M'Hidi", "Drean"],
  "Tindouf": ["Tindouf", "Oum El Assel"],
  "Tissemsilt": ["Tissemsilt", "Theniet El Had", "Bordj Bou Naama", "Lardjem"],
  "El Oued": ["El Oued", "Guemar", "Robbah", "Debila", "El M'Ghair"],
  "Khenchela": ["Khenchela", "Kaïs", "Baghaï", "Chechar"],
  "Souk Ahras": ["Souk Ahras", "Sedrata", "M'Daourouch", "Taoura"],
  "Tipaza": ["Tipaza", "Cherchell", "Hadjout", "Koléa", "Bou Ismaïl", "Fouka"],
  "Mila": ["Mila", "Ferdjioua", "Chelghoum Laïd", "Grarem Gouga"],
  "Aïn Defla": ["Aïn Defla", "Khemis Miliana", "Miliana", "El Attaf"],
  "Naâma": ["Naâma", "Mecheria", "Aïn Sefra", "Sfissifa"],
  "Aïn Témouchent": ["Aïn Témouchent", "Hammam Bouhadjar", "Chaâbat El Leham", "El Malah"],
  "Ghardaïa": ["Ghardaïa", "Metlili", "Berriane", "El Meniaa", "Guerrara"],
  "Relizane": ["Relizane", "Oued Rhiou", "Mazouna", "Zemmoura"],
  "Timimoun": ["Timimoun", "Ouled Saïd", "Charouine"],
  "Bordj Badji Mokhtar": ["Bordj Badji Mokhtar", "Timiaouine"],
  "Ouled Djellal": ["Ouled Djellal", "Sidi Khaled", "Doucen"],
  "Béni Abbès": ["Béni Abbès", "Igli", "Kerzaz"],
  "In Salah": ["In Salah", "Foggaret Ezzaouia"],
  "In Guezzam": ["In Guezzam", "Tin Zaouatine"],
  "Touggourt": ["Touggourt", "Nezla", "Tebesbest", "El Hadjira"],
  "Djanet": ["Djanet", "Bordj El Haouès"],
  "El M'Ghair": ["El M'Ghair", "Djamaa", "Still"],
  "El Meniaa": ["El Meniaa", "Hassi Gara"],
}

export const getVillesByWilaya = (wilaya) => VILLES_PAR_WILAYA[wilaya] || []
