export const WILAYAS = [
  "Adrar",
  "Chlef",
  "Laghouat",
  "Oum El Bouaghi",
  "Batna",
  "Béjaïa",
  "Biskra",
  "Béchar",
  "Blida",
  "Bouira",
  "Tamanrasset",
  "Tébessa",
  "Tlemcen",
  "Tiaret",
  "Tizi Ouzou",
  "Alger",
  "Djelfa",
  "Jijel",
  "Sétif",
  "Saïda",
  "Skikda",
  "Sidi Bel Abbès",
  "Annaba",
  "Guelma",
  "Constantine",
  "Médéa",
  "Mostaganem",
  "M'Sila",
  "Mascara",
  "Ouargla",
  "Oran",
  "El Bayadh",
  "Illizi",
  "Bordj Bou Arréridj",
  "Boumerdès",
  "El Tarf",
  "Tindouf",
  "Tissemsilt",
  "El Oued",
  "Khenchela",
  "Souk Ahras",
  "Tipaza",
  "Mila",
  "Aïn Defla",
  "Naâma",
  "Aïn Témouchent",
  "Ghardaïa",
  "Relizane",
  "Timimoun",
  "Bordj Badji Mokhtar",
  "Ouled Djellal",
  "Béni Abbès",
  "In Salah",
  "In Guezzam",
  "Touggourt",
  "Djanet",
  "El M'Ghair",
  "El Meniaa",
];

// أهم البلديات لكل ولاية — تُستعمل لملء قائمة "المدينة" تلقائياً حسب الولاية المختارة
export const CITIES_BY_WILAYA = {
  "Adrar": ["Adrar", "Reggane", "Aoulef", "Tsabit", "Fenoughil", "Zaouiet Kounta", "Charouine", "Sebaa"],
  "Chlef": ["Chlef", "Ténès", "Boukadir", "Oued Fodda", "Chettia", "Ouled Farès", "Sobha", "El Karimia"],
  "Laghouat": ["Laghouat", "Aflou", "Ksar El Hirane", "Hassi R'Mel", "Aïn Madhi", "Gueltat Sidi Saâd"],
  "Oum El Bouaghi": ["Oum El Bouaghi", "Aïn Beïda", "Aïn M'lila", "Ksar Sbahi", "Meskiana", "Sigus"],
  "Batna": ["Batna", "Merouana", "Barika", "Arris", "N'Gaous", "Tazoult", "Ras El Aïoun", "Seriana"],
  "Béjaïa": ["Béjaïa", "Akbou", "Amizour", "Kherrata", "Sidi Aïch", "Tichy", "El Kseur", "Aokas"],
  "Biskra": ["Biskra", "Tolga", "Sidi Okba", "Zeribet El Oued", "El Kantara", "Ouled Djellal Ancien", "El Outaya"],
  "Béchar": ["Béchar", "Kenadsa", "Abadla", "Béni Ounif", "Taghit", "Lahmar"],
  "Blida": ["Blida", "Boufarik", "Bouinan", "Ouled Yaïch", "Mouzaïa", "Larbaâ", "El Affroun", "Chréa"],
  "Bouira": ["Bouira", "Sour El Ghozlane", "Lakhdaria", "Kadiria", "M'Chedallah", "Aïn Bessem"],
  "Tamanrasset": ["Tamanrasset", "Abalessa", "Idlès", "Tazrouk", "In Amguel"],
  "Tébessa": ["Tébessa", "Bir El Ater", "Chéria", "El Aouinet", "Ouenza", "El Kouif"],
  "Tlemcen": ["Tlemcen", "Maghnia", "Ghazaouet", "Nedroma", "Remchi", "Sebdou", "Mansourah"],
  "Tiaret": ["Tiaret", "Sougueur", "Frenda", "Mahdia", "Ksar Chellala", "Aïn Deheb"],
  "Tizi Ouzou": ["Tizi Ouzou", "Azazga", "Draâ El Mizan", "Larbaâ Nath Irathen", "Boghni", "Azeffoun", "Aïn El Hammam"],
  "Alger": ["Alger Centre", "Bab El Oued", "Hussein Dey", "El Harrach", "Bir Mourad Raïs", "Kouba", "Bab Ezzouar", "Dar El Beïda", "Bordj El Kiffan", "Aïn Benian", "Zeralda", "Rouiba", "Réghaïa", "Baraki", "Draria", "Cheraga"],
  "Djelfa": ["Djelfa", "Messaad", "Hassi Bahbah", "Aïn Oussera", "Charef", "Aïn El Ibel"],
  "Jijel": ["Jijel", "Taher", "El Milia", "Chekfa", "Ziama Mansouriah", "Settara"],
  "Sétif": ["Sétif", "El Eulma", "Aïn Oulmène", "Bougaâ", "Bir El Arch", "Aïn El Kebira", "Aïn Azel"],
  "Saïda": ["Saïda", "Aïn El Hadjar", "Youb", "Sidi Boubekeur", "Doui Thabet"],
  "Skikda": ["Skikda", "Azzaba", "Collo", "El Harrouch", "Ramdane Djamel", "Tamalous", "Filfila"],
  "Sidi Bel Abbès": ["Sidi Bel Abbès", "Télagh", "Ben Badis", "Sfisef", "Mostefa Ben Brahim", "Ras El Ma"],
  "Annaba": ["Annaba", "El Bouni", "El Hadjar", "Berrahal", "Séraïdi", "Aïn Berda"],
  "Guelma": ["Guelma", "Oued Zenati", "Héliopolis", "Bouchegouf", "Hammam Debagh"],
  "Constantine": ["Constantine", "El Khroub", "Hamma Bouziane", "Didouche Mourad", "Aïn Smara", "Zighoud Youcef"],
  "Médéa": ["Médéa", "Berrouaghia", "Ksar El Boukhari", "Tablat", "Aïn Boucif", "Ouzera"],
  "Mostaganem": ["Mostaganem", "Sidi Ali", "Bouguirat", "Sayada", "Achaacha", "Aïn Tédelès"],
  "M'Sila": ["M'Sila", "Bou Saâda", "Sidi Aïssa", "Magra", "Aïn El Melh", "Hammam Dalaa"],
  "Mascara": ["Mascara", "Tighennif", "Sig", "Ghriss", "Mohammadia", "Bouhanifia"],
  "Ouargla": ["Ouargla", "Hassi Messaoud", "N'Goussa", "Rouissat", "Aïn Beïda"],
  "Oran": ["Oran", "Es Sénia", "Bir El Djir", "Aïn Turk", "Arzew", "Bethioua", "Gdyel", "Bousfer"],
  "El Bayadh": ["El Bayadh", "Bougtoub", "Rogassa", "El Abiodh Sidi Cheikh", "Boualem"],
  "Illizi": ["Illizi", "In Amenas", "Bordj Omar Driss"],
  "Bordj Bou Arréridj": ["Bordj Bou Arréridj", "Ras El Oued", "Medjana", "El Achir", "Bordj Ghdir"],
  "Boumerdès": ["Boumerdès", "Boudouaou", "Thenia", "Dellys", "Bordj Menaïel", "Naciria", "Zemmouri"],
  "El Tarf": ["El Tarf", "Bouhadjar", "Ben M'Hidi", "El Kala", "Drean", "Bouteldja"],
  "Tindouf": ["Tindouf", "Oum El Assel"],
  "Tissemsilt": ["Tissemsilt", "Theniet El Had", "Bordj Bou Naâma", "Lardjem"],
  "El Oued": ["El Oued", "Robbah", "Guemar", "Debila", "Djamaa", "Reguiba"],
  "Khenchela": ["Khenchela", "Kaïs", "Chechar", "El Hamma", "Baghai"],
  "Souk Ahras": ["Souk Ahras", "Sedrata", "Mechroha", "Zaarouria"],
  "Tipaza": ["Tipaza", "Cherchell", "Hadjout", "Koléa", "Fouka", "Bou Ismaïl", "Damous"],
  "Mila": ["Mila", "Ferdjioua", "Chelghoum Laïd", "Grarem Gouga", "Oued Athmania"],
  "Aïn Defla": ["Aïn Defla", "Khemis Miliana", "El Attaf", "Miliana", "Djelida"],
  "Naâma": ["Naâma", "Mécheria", "Aïn Sefra", "Sfissifa"],
  "Aïn Témouchent": ["Aïn Témouchent", "Hammam Bouhadjar", "Béni Saf", "El Amria"],
  "Ghardaïa": ["Ghardaïa", "Metlili", "El Atteuf", "Berriane", "Guerrara", "Zelfana"],
  "Relizane": ["Relizane", "Oued Rhiou", "Mazouna", "Ammi Moussa", "Yellel"],
  "Timimoun": ["Timimoun", "Ouled Saïd", "Charouine", "Aougrout"],
  "Bordj Badji Mokhtar": ["Bordj Badji Mokhtar", "Timiaouine"],
  "Ouled Djellal": ["Ouled Djellal", "Sidi Khaled", "Doucen", "Besbes"],
  "Béni Abbès": ["Béni Abbès", "Igli", "Kerzaz", "Timoudi"],
  "In Salah": ["In Salah", "Foggaret Ezzaouia", "In Ghar"],
  "In Guezzam": ["In Guezzam", "Tin Zaouatine"],
  "Touggourt": ["Touggourt", "Nezla", "Tebesbest", "El Hadjira", "Megarine"],
  "Djanet": ["Djanet", "Bordj El Haouas"],
  "El M'Ghair": ["El M'Ghair", "Sidi Amrane", "Still", "Djamaa Ancien"],
  "El Meniaa": ["El Meniaa", "Hassi Gara"],
};
